import type { CurvedLoopItem } from "@/components/about/CurvedLoop";

export const carouselItems: CurvedLoopItem[] = [
  { src: "/about-carousel/aws-svgrepo-com.svg", alt: "AWS" },
  { src: "/about-carousel/capcut-icon.svg", alt: "CapCut" },
  { src: "/about-carousel/cuda-svgrepo-com.svg", alt: "CUDA" },
  { src: "/about-carousel/dartlang-ar21.svg", alt: "Dart" },
  { src: "/about-carousel/engine-prime.png", alt: "Engine Prime" },
  { src: "/about-carousel/expressjs-ar21.svg", alt: "Express.js" },
  { src: "/about-carousel/firebase-icon.svg", alt: "Firebase" },
  { src: "/about-carousel/figma-logo-svgrepo-com.svg", alt: "Figma" },
  { src: "/about-carousel/icon-flutter.svg", alt: "Flutter" },
  { src: "/about-carousel/hf-logo.svg", alt: "Hugging Face" },
  { src: "/about-carousel/java-ar21.svg", alt: "Java" },
  { src: "/about-carousel/javascript-logo-svgrepo-com.svg", alt: "JavaScript" },
  { src: "/about-carousel/logic-logo.png", alt: "Logic Pro" },
  { src: "/about-carousel/matlab.svg", alt: "MATLAB" },
  { src: "/about-carousel/mongodb-ar21.svg", alt: "MongoDB" },
  { src: "/about-carousel/nextjs-icon-svgrepo-com.svg", alt: "Next.js" },
  { src: "/about-carousel/nodejs-icon-svgrepo-com.svg", alt: "Node.js" },
  { src: "/about-carousel/php-svgrepo-com.svg", alt: "PHP" },
  { src: "/about-carousel/postgresql-logo-svgrepo-com.svg", alt: "PostgreSQL" },
  { src: "/about-carousel/python-svgrepo-com.svg", alt: "Python" },
  { src: "/about-carousel/pytorch-ar21.svg", alt: "PyTorch" },
  { src: "/about-carousel/r-project-icon.svg", alt: "R" },
  { src: "/about-carousel/react-svgrepo-com.svg", alt: "React" },
  { src: "/about-carousel/recordbox.png", alt: "rekordbox" },
  { src: "/about-carousel/redis-logo-svgrepo-com.svg", alt: "Redis" },
  { src: "/about-carousel/serato-dj-pro-vector-logo.svg", alt: "Serato DJ Pro" },
  { src: "/about-carousel/solidworks-logo-1.svg", alt: "SOLIDWORKS" },
  { src: "/about-carousel/soundswitch-logo.png", alt: "SoundSwitch" },
  { src: "/about-carousel/sql-database-generic-svgrepo-com.svg", alt: "SQL" },
  { src: "/about-carousel/stata.svg", alt: "Stata" },
  { src: "/about-carousel/swift-programming-language-logo.svg", alt: "Swift" },
  { src: "/about-carousel/tableau-svgrepo-com.svg", alt: "Tableau" },
  { src: "/about-carousel/tensorflow-ar21.svg", alt: "TensorFlow" },
  { src: "/about-carousel/typescript-svgrepo-com.svg", alt: "TypeScript" },
  { src: "/about-carousel/vllm-color.svg", alt: "vLLM" },
];
