name: Update Stock Prices & GitHub Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: write  # Allow workflow to write to repository

jobs:
  update-data:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      
      - name: Install dependencies
        run: |
          pip install yfinance requests
      
      - name: Fetch stock data
        run: python scripts/fetch_stocks.py
      
      - name: Fetch GitHub stats
        run: python scripts/fetch_github_stats.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Commit and push if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add assets/data/*.json
          if git diff --quiet && git diff --staged --quiet; then
            echo "No changes to commit"
          else
            git commit -m "Update stock prices and GitHub stats [skip ci]"
            # Use force-with-lease to handle conflicts safely
            git push origin main --force-with-lease
          fi
